### ISSUE TITLE
Inconsistencies with outputs of otp_gen and password_gen_control functions.

### ISSUE THREAD

**Issue by Urias-T** [bgraphixx/SafeTokenGen#1]
First, @bgraphixx great work here. Really love what you've built. 

I've noticed that on multiple runs, the `otp_gen` and `password_gen_control` functions might return unreliable results. Specifically, I can tell that when the 'otp_gen' function is run with the `alpha_numeric` parameter set to True, it could return a string of letters only. Which by definition isn't alpha-numeric.

I haven't investigated the 'password_gen_control' function enough yet to know exactly what it returns to fail its unit test on some runs.

In all, my number one suspect is the 'random' module. which is used to populate the function responses. There's always the probability that the chosen characters don't exactly meet the expected criteria.

**Comment by bgraphixx** [comment]
Thank you first of all for checking it out. I appreciate it

I'm going to have a look at those functions and run more extensive tests as I didn't get these results earlier. I would also see how best to optimize them so they adhere to the parameters set as well as have a short run time.

**Comment by bgraphixx** [comment]
@Urias-T I've added a checker. This should simulate the proper results every time an output is generated. I also added a minimum length exception for otp(2 - there are two criteria) and password(4 - there are four criteria), so an infinite loop is not triggered when the criteria set are not met.

**Comment by Urias-T** [comment]
Hey, @bgraphixx the `password_gen_control` function was still failing its test intermittently. I figured it was as a result of the fact that the function itself uses `string.punctuation` (which has about 32 possible output characters) to create the passwords whereas, the test file was testing with a limited string of about 20-something symbols.

This PR (#5) fixes that by also using `string.punctuation` to test the function.

**Comment by bgraphixx** [comment]
Hi @Urias-T, thank you for your contribution so far. I'll take a look at this PR

**Comment by bgraphixx** [comment]
Hi @Urias-T, thank you for your contribution so far. I'll take a look at this PR

**Comment by bgraphixx** [comment]
Hi @Urias-T, thank you for your contribution so far. I'll take a look at this PR
